Change time calculations and time difference displays
twohoursonelife/dictator pull request #119
Opened 2023-09-03 12:22 UTC by TanyaPegasus

Updated methods used to calculate time differences for /info and /whowas commands, and also changed how those difference display in embeds.

2023-09-03 13:02 UTC, connorhsm requested changes
Looks great! Much cleaner way to process the times and then display.

I've nitpicked a lot here because I know you don't have a full dev environment set up, which would usually catch a lot more of these things before a PR. Please forgive me; You have done a great job.

2023-09-03 13:18 UTC, TanyaPegasus commented on dictator/cogs/informational.py
> +import humanize
Sorry, really didn't mean to do that

2023-09-03 14:09 UTC, TanyaPegasus commented on dictator/cogs/informational.py
> +        embed.add_field(name="Last activity:", value=f"{difference}")
We talked about that mostly in relation to the whowas command I think, but it's using the same code as this anyway. I tested a few different dates and all showed only 1 time period. I'll will test more with a greater variety of dates. I'll also look through the humanize code again. 
The logic behind what displays here is almost entirely in the humanize module. If it turns out that method won't work, we will need precisedelta, with our own logic to decide what displays when. I need to remind myself how that works, but it's likely to be quite a few more lines of code and a bit less clean. Is that preferred?

2023-09-06 14:07 UTC, connorhsm commented on dictator/cogs/informational.py
> +        embed.add_field(name="Last activity:", value=f"{difference}")
Reconsidering, this is fine as is. Thanks for clarifying.

2023-09-06 14:17 UTC, merged